/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Sweet as PrismaSweet } from "@prisma/client";

export class SweetServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.SweetCountArgs, "select">): Promise<number> {
    return this.prisma.sweet.count(args);
  }

  async sweets(args: Prisma.SweetFindManyArgs): Promise<PrismaSweet[]> {
    return this.prisma.sweet.findMany(args);
  }
  async sweet(args: Prisma.SweetFindUniqueArgs): Promise<PrismaSweet | null> {
    return this.prisma.sweet.findUnique(args);
  }
  async createSweet(args: Prisma.SweetCreateArgs): Promise<PrismaSweet> {
    return this.prisma.sweet.create(args);
  }
  async updateSweet(args: Prisma.SweetUpdateArgs): Promise<PrismaSweet> {
    return this.prisma.sweet.update(args);
  }
  async deleteSweet(args: Prisma.SweetDeleteArgs): Promise<PrismaSweet> {
    return this.prisma.sweet.delete(args);
  }
}
