/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SweetService } from "../sweet.service";
import { SweetCreateInput } from "./SweetCreateInput";
import { Sweet } from "./Sweet";
import { SweetFindManyArgs } from "./SweetFindManyArgs";
import { SweetWhereUniqueInput } from "./SweetWhereUniqueInput";
import { SweetUpdateInput } from "./SweetUpdateInput";

export class SweetControllerBase {
  constructor(protected readonly service: SweetService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Sweet })
  async createSweet(@common.Body() data: SweetCreateInput): Promise<Sweet> {
    return await this.service.createSweet({
      data: data,
      select: {
        category: true,
        createdAt: true,
        id: true,
        name: true,
        price: true,
        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Sweet] })
  @ApiNestedQuery(SweetFindManyArgs)
  async sweets(@common.Req() request: Request): Promise<Sweet[]> {
    const args = plainToClass(SweetFindManyArgs, request.query);
    return this.service.sweets({
      ...args,
      select: {
        category: true,
        createdAt: true,
        id: true,
        name: true,
        price: true,
        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Sweet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async sweet(
    @common.Param() params: SweetWhereUniqueInput
  ): Promise<Sweet | null> {
    const result = await this.service.sweet({
      where: params,
      select: {
        category: true,
        createdAt: true,
        id: true,
        name: true,
        price: true,
        quantity: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Sweet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSweet(
    @common.Param() params: SweetWhereUniqueInput,
    @common.Body() data: SweetUpdateInput
  ): Promise<Sweet | null> {
    try {
      return await this.service.updateSweet({
        where: params,
        data: data,
        select: {
          category: true,
          createdAt: true,
          id: true,
          name: true,
          price: true,
          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Sweet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSweet(
    @common.Param() params: SweetWhereUniqueInput
  ): Promise<Sweet | null> {
    try {
      return await this.service.deleteSweet({
        where: params,
        select: {
          category: true,
          createdAt: true,
          id: true,
          name: true,
          price: true,
          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
