/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Sweet } from "./Sweet";
import { SweetCountArgs } from "./SweetCountArgs";
import { SweetFindManyArgs } from "./SweetFindManyArgs";
import { SweetFindUniqueArgs } from "./SweetFindUniqueArgs";
import { CreateSweetArgs } from "./CreateSweetArgs";
import { UpdateSweetArgs } from "./UpdateSweetArgs";
import { DeleteSweetArgs } from "./DeleteSweetArgs";
import { SweetService } from "../sweet.service";
@graphql.Resolver(() => Sweet)
export class SweetResolverBase {
  constructor(protected readonly service: SweetService) {}

  async _sweetsMeta(
    @graphql.Args() args: SweetCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Sweet])
  async sweets(@graphql.Args() args: SweetFindManyArgs): Promise<Sweet[]> {
    return this.service.sweets(args);
  }

  @graphql.Query(() => Sweet, { nullable: true })
  async sweet(
    @graphql.Args() args: SweetFindUniqueArgs
  ): Promise<Sweet | null> {
    const result = await this.service.sweet(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Sweet)
  async createSweet(@graphql.Args() args: CreateSweetArgs): Promise<Sweet> {
    return await this.service.createSweet({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Sweet)
  async updateSweet(
    @graphql.Args() args: UpdateSweetArgs
  ): Promise<Sweet | null> {
    try {
      return await this.service.updateSweet({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Sweet)
  async deleteSweet(
    @graphql.Args() args: DeleteSweetArgs
  ): Promise<Sweet | null> {
    try {
      return await this.service.deleteSweet(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
